name: ReSplash-CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'
    pull_request:
      branches:
        - master
        - develop
        - 'feature/**'
        - 'fix/**'

jobs:
  setupJDK:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

  ktlintFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run KtLint format
        run: ./gradlew ktlintFormat

  buildApkFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build Android APK file
        run: ./gradlew androidApp:assembleDebug

      - name: Save APK file
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: androidApp/build/outputs/apk/debug/
