name: ReSplash-CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'
    pull_request:
      branches:
        - master
        - develop
        - 'feature/**'
        - 'fix/**'

jobs:
  sendCommitNotificationOnPush:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Author: ${{ github.actor }}
            pushed new commit ${{ github.event.commits[0].message }}
            to repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  setupJDK:
    needs: sendCommitNotificationOnPush
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

  ktlintFormat:
    needs: setupJDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run KtLint format
        run: ./gradlew ktlintFormat



  
