name: ReSplash-CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'
    pull_request:
      branches:
        - master
        - develop
        - 'feature/**'
        - 'fix/**'

jobs:
  sendCommitNotificationOnPush:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Author: ${{ github.actor }}
            pushed new commit - ${{ github.event.commits[0].message }}
            to repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  sendChangelogToTelegram:
    runs-on: ubuntu-latest
    steps:
      run: |
        git log --pretty=format:'%an %h %s' -n 5 --abbrev-commit >> output.txt        
        - name: Send git changelog to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          $(cat output.txt)


  setupJDK:
    needs: [ sendCommitNotificationOnPush, sendChangelogToTelegram ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

  ktlintFormat:
    needs: setupJDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run KtLint format
        run: ./gradlew ktlintFormat

  buildApkFile:
    needs: ktlintFormat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Build Android APK file
        run: ./gradlew androidApp:assembleDebug
      - name: Save APK file
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: androidApp/build/outputs/apk/debug/

