name: resplash kmm ci

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  KTLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check codestyle
        uses: ./.github/workflows/ktlint.yaml

  buildDebugApk:
    needs: [KTLint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Debug Apk
        uses: ./.github/workflows/build_debug_apk.yaml
