name: resplash kmm ci

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  KTLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check codestyle
        extends: ./ktlint.yaml

  buildDebugApk:
    needs: [KTLint]
    runs-on: ubuntu-latest
    steps:
      - name: Build Debug Apk
        extends: ./build_debug_apk.yaml
