name: resplash kmm ci

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  KTLint Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check codestyle
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - name: Run KtLint check
        run: ./gradlew ktlintCheck

  Build Debug Apk:
    needs: [ KTLint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Build Android APK file
        run: ./gradlew androidApp:assembleDebug
      - name: Save APK file
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: androidApp/build/outputs/apk/debug/
